-- Create bookings table
create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  restaurant_id text references public.restaurants(id) on delete cascade,
  table_id text not null,
  guest_name text,
  guest_phone text,
  guest_count int,
  booking_date text not null,
  booking_time text not null,
  slot_key text not null,
  status text default 'pending',
  image_path text,
  notes text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Enable RLS
alter table public.bookings enable row level security;

-- Policies

-- Users can view their own bookings
create policy "Users can view own bookings"
  on bookings for select
  using ( auth.uid() = user_id );

-- Users can create bookings
create policy "Users can create bookings"
  on bookings for insert
  with check ( auth.uid() = user_id );

-- Users can update their own bookings
create policy "Users can update own bookings"
  on bookings for update
  using ( auth.uid() = user_id );

-- Restaurant owners can view bookings for their restaurant
create policy "Owners can view bookings for their restaurant"
  on bookings for select
  using ( 
    exists (
      select 1 from restaurants
      where restaurants.id = bookings.restaurant_id
      and restaurants.owner_id = auth.uid()
    )
  );

-- Restaurant owners can update bookings for their restaurant
create policy "Owners can update bookings for their restaurant"
  on bookings for update
  using ( 
    exists (
      select 1 from restaurants
      where restaurants.id = bookings.restaurant_id
      and restaurants.owner_id = auth.uid()
    )
  );
